services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=testuser
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=testdb
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: github-service-db
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

