services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-service
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  db:
    image: postgres:15
    container_name: github-service-db
    ports:
    - 5432:5432
    restart: always
    user: 1000:1000
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  app-network:
    driver: bridge

