basePath: /
definitions:
  data.Author:
    properties:
      commits:
        items:
          $ref: '#/definitions/data.Commit'
        type: array
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  data.Commit:
    properties:
      author:
        $ref: '#/definitions/data.Author'
      authorID:
        type: integer
      commitHash:
        type: string
      createdAt:
        type: string
      date:
        type: string
      id:
        type: integer
      message:
        type: string
      repositoryID:
        type: integer
    type: object
  data.Repository:
    properties:
      commits:
        items:
          $ref: '#/definitions/data.Commit'
        type: array
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      ownerName:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an indexer for github.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Github Service API
  version: "1.0"
paths:
  /commits:
    get:
      consumes:
      - application/json
      description: Get commits for a specific repository by its name
      parameters:
      - description: Repository Name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Commit'
            type: array
      summary: Get commits by repository name
      tags:
      - commits
  /repositories:
    post:
      consumes:
      - application/json
      description: Add a new repository to be tracked
      parameters:
      - description: Repository Data
        in: body
        name: repository
        required: true
        schema:
          $ref: '#/definitions/data.Repository'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/data.Repository'
      summary: Add a new repository
      tags:
      - repositories
  /top-authors:
    get:
      consumes:
      - application/json
      description: Get the top N commit authors by commit counts
      parameters:
      - description: Number of top authors
        in: query
        name: limit
        required: true
        type: integer
      - description: Repo name
        in: query
        name: repo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Author'
            type: array
      summary: Get top N commit authors
      tags:
      - commits
swagger: "2.0"
